projects:
  - name: node-workers-example
    environments:
      - name: production
        services:
          # Web service (from Heroku web dyno)
          - type: web
            name: node-workers-web
            runtime: node
            plan: starter
            region: oregon
            buildCommand: npm install
            startCommand: pm2 start pm2.config.cjs --only server --no-daemon --attach
            envVars:
              - key: NODE_ENV
                value: production
              - key: REDIS_URL
                fromService:
                  type: keyvalue
                  name: node-workers-cache
                  property: connectionString
              - fromGroup: node-workers-env

          # Background worker (from Heroku worker dyno)
          - type: worker
            name: node-workers-worker
            runtime: node
            plan: starter
            region: oregon
            buildCommand: npm install
            startCommand: pm2 start pm2.config.cjs --only worker --no-daemon --attach
            envVars:
              - key: NODE_ENV
                value: production
              - key: REDIS_URL
                fromService:
                  type: keyvalue
                  name: node-workers-cache
                  property: connectionString
              - fromGroup: node-workers-env

          # Key Value store (from Heroku Redis add-on)
          - type: keyvalue
            name: node-workers-cache
            plan: starter
            ipAllowList:
              - source: 0.0.0.0/0
                description: everywhere

        envVarGroups:
          - name: node-workers-env
            envVars:
              - key: WEB_CONCURRENCY
                value: "1"
